### ISSUE TITLE
Video of other side is scrambled

### ISSUE THREAD

**Issue by sidan5** [relatedcode/Messenger#190]
Voice is fine but other side video is not shown properly.
![IMG_F4157E491031-1](https://user-images.githubusercontent.com/1595490/71113193-c2501400-21d5-11ea-9734-c78d1f049287.jpeg)

**Comment by relatedcode** [comment]
@sidan5 Thanks for the feedback. The video call feature update is in progress.

**Comment by theappshed** [comment]
Hello!
It seems that the scrambled video is to do with encoding in iOS13 - I may be wrong. When I call from iOS12 to iOS 13, the video sent FROM iOS12 display correctly on the iOS13 handset, but not the other way around. 

When calling 13 to 13 the video is scrambled on both screens.

Is this due to the Sinch version being '3.12.9', whereas the latest version is 4+

Thanks,
Steve

**Comment by theappshed** [comment]
Been reading through Sinch FAQs and docs and this scrambling is a known issue in iOS13 with Sinch.
They released a new pod update to cover the requirements, but it will mean changing some of their deprecated methods in this demo app. I'll keep you updated as to my findings over the coming days.


Strangely enough the scrambling disappears if you go landscape rather than portrait!

**Comment by relatedcode** [comment]
Thanks for the feedback. The Sinch VoIP related update is in progress.

**Comment by theappshed** [comment]
No worries buddy - any idea on ETA? (Just a rough guess)

**Comment by theappshed** [comment]
I've managed to update the core Sinch version to 4.1. I have had to remove: 

- SINSLazyMessageClient.h and .m as they are no longer supported in Sinch
- SINService.h - Comment out Line 73
- AppDelegate.swift - Comment out Lines 312-319 as the Local Notification function is no longer supported within Sinch
- SINService.m - Comment out lines 210, 217 & 227. Also comment out the LazyMessage import and any uses of "messageClient"

This gets the video temporarily working, but there is now no longer a method of accepting a call in the background - that's the last hurdle to fix

Steve

**Comment by oskarko** [comment]
Any update with this issue? @theappshed ?

**Comment by theappshed** [comment]
@oskarko Have you followed the steps I showed above buddy?

**Comment by oskarko** [comment]
“ but there is now no longer a method of accepting a call in the background - that's the last hurdle to fix” even this one is fixed with your steps?

**Comment by relatedcode** [comment]
The Sinch SDK has been update to the latest version. Please check now. Thanks!
